[FIX] Refactor setToast method to prevent incorrect display of toasts (1035)
sunflower-land/sunflower-land pull request #1153
Opened 2022-06-27 09:59 UTC by AzaroQL

# Description

Refactored setToast method to set state only once. 
Increased max toast amount to 6(from 5) since we have a lot of recipes that require 3 ingredients.

Fixes [#1035](https://github.com/sunflower-land/sunflower-land/issues/1035)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Manual test, yarn test

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [n/a] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-06-30 02:29 UTC, spencerdezartsmith requested changes
Awesome fix. I am hesitant to increase the max toast though because 5 can already be pretty intense on mobile as in it can block you from doing certain actions. 

What if we made the toast smaller on mobile?

2022-06-30 02:29 UTC, spencerdezartsmith commented on src/features/game/toast/ToastQueueProvider.tsx
> +    const newToast = { id: id, ...toast };
This can just be `{ id, ...toast }`

2022-06-30 06:34 UTC, AzaroQL commented on src/features/game/toast/ToastQueueProvider.tsx
> +    const newToast = { id: id, ...toast };
fixed

2022-06-30 06:35 UTC, AzaroQL commented
Reverted back to 5. Regarding the size, I guess it should be done as a separate PR.

2022-07-01 04:44 UTC, spencerdezartsmith approved these changes

2022-07-01 04:44 UTC, merged