[FIX] Moles still act as tiered on Bank Withdraw
sunflower-land/sunflower-land pull request #1164
Opened 2022-07-01 09:23 UTC by Ant-Redstone

Moles got their buffs split, but the withdraw function from bank didn't get updated, so as example, Nugget or Rocky the Mole can't be withdraw if there is a stone being replenished, while they should be withdrawable
Some server-sided changes might be needed.

# Description

I have removed the checks for the wrong ores from mole on bankUtils and bankUtils.test

Fixes #1163

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I didn't test those changes at all, I don't know how I would be able to withdraw moles on testnet, since I don't have em in there.

# Checklist:
(tbh idk if I should mark all of those)

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-07-02 02:40 UTC, j923sneaks requested changes
Small suggestion: put `stoneReady` `ironReady` `goldReady` inside corresponding conditions so it will only execute when necessary

for stone
```
// Make sure stones are not replenishing
if (item === "Tunnel Mole") {
  const stoneReady = Object.values(game?.stones).every((stone) =>
    canMine(stone)
  );
  return stoneReady;
}
```

2022-07-04 01:52 UTC, c-py commented
@Ant-Redstone Nice work! Would you mind fixing up the linting error which the CI is currently failing on?

I can work on the server side changes to match your frontend changes.

2022-07-04 08:36 UTC, Ant-Redstone commented
> @Ant-Redstone Nice work! Would you mind fixing up the linting error which the CI is currently failing on?
> 
> I can work on the server side changes to match your frontend changes.

yeah sure, sorry, I missed that error, when I did the patch

2022-07-04 08:45 UTC, Ant-Redstone commented
Should be fixed, is weird cuz when I `yarn lint` I get a ton of errors of a weird character, idk if my files are opening with wrong formatting or what
so its kinda hard to spot in here, only when u run it through github

If you know how to fix, I'd be happy, oh and when I do `yarn install` I can't push anymore, I get and error saying `'bash' no such file or directory` or something like that

2022-07-06 00:48 UTC, c-py approved these changes
Awesome @Ant-Redstone 👍👍👍 ! I have implemented the backend changes as well so I will merge your contribution in 🎉

2022-07-06 00:48 UTC, merged