[FEAT] Water Deco
sunflower-land/sunflower-land pull request #1198
Opened 2022-07-07 22:00 UTC by Rofrtd

# Description

Add static wave image to land expansion background and a few water decorations.

<img width="741" alt="Screen Shot 2022-07-07 at 7 12 56 pm" src="https://user-images.githubusercontent.com/25412194/177880306-9ec92a40-652e-4f7c-b238-4057cf212eb1.png">

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-07-07 23:09 UTC, adamhannigan requested changes
Nice work mate! The ocean is coming to life 🌊 

We just need to be consistent in the pixel sizes of the objects to make sure everything is perfect. We want to set a benchmark/standard for pixel perfect sizes now that we have a clean slate.

I've left a few suggestions around resizing some of the artwork to keep the pixel size consistent

2022-07-07 23:09 UTC, adamhannigan commented on src/features/game/expansion/components/Water.tsx
> +      <Shark side="top" />
The shark pixels appear much larger than the water pixels. For consistency we need to ensure that all of the pixels are the same size.

I would suggest scaling the shark down so it is the same size as some of the pixels you see on the land - such as the pebble or crop.

<img width="303" alt="Screen Shot 2022-07-08 at 9 02 47 am" src="https://user-images.githubusercontent.com/11745561/177885655-91e79967-cbf6-44c1-a9d4-774acbf3f45c.png">

2022-07-07 23:09 UTC, adamhannigan commented on src/features/game/expansion/LandExpansion.tsx
> +              style={{ backgroundImage: `url(${waterMovement})` }}
If you look closely, the water appears quite blurry. Consider adding the pixelated image rendering to the background image.

It also appears that the water pixels are smaller than the land pixels. We need to get the water pixel sizes perfect from the beginning as we will use this to size a range of objects on the water.

Try to scale the water so it correctly matches the pixel size of the land.

<img width="410" alt="Screen Shot 2022-07-08 at 9 04 54 am" src="https://user-images.githubusercontent.com/11745561/177885802-021c5ff9-29d2-47c3-a47b-2f8e94071ab0.png">

2022-07-07 23:09 UTC, adamhannigan commented on src/features/game/expansion/components/Water.tsx
> +          className="absolute left-2/3 top-1/2 animate-float"
<img width="215" alt="Screen Shot 2022-07-08 at 9 02 06 am" src="https://user-images.githubusercontent.com/11745561/177885952-40f0f3ec-f8b1-4988-8284-431f92fbe8d6.png">

Just another small one, but the dragonfly pixels are much larger than the water pixels

2022-07-10 19:16 UTC, Z1kou commented
Just an opinion, 

I would refrain from adding any swimming goblins / farmers to the farmers As I don't think it will fit the lore we want of getting haunted from a continent on an island and being extremly limited on human/gob ressource's 

Same thing with the dragon flies that would never exist near salty water, Maybe we replace the with other small sea creature's, like shrimps or shells ect

This is just me trying to put the lore of the game into action and since we are in a "magical" world all i said can be ommited  🤣

2022-07-14 00:14 UTC, adamhannigan approved these changes
Nice work mate! Looks much more consistent 💪

2022-07-14 00:14 UTC, merged