[FEAT] Deep-Link to Farm Listings
sunflower-land/sunflower-land pull request #1378
Opened 2022-08-31 00:57 UTC by ShiningMinions

# Description

This PR implements a deep-linking strategy to go directly to a farm's listings given a magic URL. This feature will help support third-party listing tools (like https://sfl.tools), allowing buyers to be taken directly to a farm's listings at the click of a button.

Fixes + Read More Here: https://github.com/sunflower-land/sunflower-land/issues/1366

Code works in the following way:
1. Enter a URL like the following: `{URL}/#/goblins?viewListingsForLand=1`
2. After game load (and if needed, after auth flow), bypass the splash screen and load directly into goblin town.
3. Auto-display the trader modal, with `Land ID 1`'s current trades.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

https://user-images.githubusercontent.com/103600068/187569166-ee2029f5-48e0-4a16-aaed-03b94931f244.mp4

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-31 12:52 UTC, veenhdek commented
🚀 fantastic work! As always!

2022-09-01 02:17 UTC, c-py requested changes

2022-09-01 02:17 UTC, c-py commented on src/features/goblins/trader/tradingPost/Trader.tsx
> +    const modifiedParams = Object.assign({}, searchParams);
```suggestion
    const modifiedParams = new URLSearchParams(searchParams);
```

Awesome PR @ShiningMinions ! 🎉 

It's working really nicely. I did encounter one small issue testing. When closing the trader modal, I got the error below on Firefox:

`Uncaught TypeError: modifiedParams.delete is not a function`.

Replacing `modifiedParams` with `const modifiedParams = new URLSearchParams(searchParams);
` seems to resolve this issue.

2022-09-01 03:20 UTC, ShiningMinions commented
@c-py done :+1:

2022-09-01 03:46 UTC, c-py approved these changes
Looking good mate! Excellent addition!

2022-09-01 03:49 UTC, merged