[FEAT] Incubator - Community Garden
sunflower-land/sunflower-land pull request #1589
Opened 2022-10-31 21:35 UTC by tiffanydys

# Description
Tadpole incubator, incubate your tadpole + frog for whitelist token rewards 😄

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
`yarn dev`

<img width="499" alt="Screen Shot 2022-10-27 at 9 49 15 PM" src="https://user-images.githubusercontent.com/18549210/199114360-7b35f605-1c88-4e14-ad6b-f57e4058b1fe.png">
<img width="505" alt="Screen Shot 2022-10-27 at 11 07 40 PM" src="https://user-images.githubusercontent.com/18549210/199114424-412e3ec4-5849-4020-8c0f-10ff19d11b69.png">
<img width="500" alt="Screen Shot 2022-11-01 at 4 59 04 AM" src="https://user-images.githubusercontent.com/18549210/199114269-87158782-ee1e-41e5-ae0b-384b2cdf7fc3.png">

`yarn test`
<img width="592" alt="Screen Shot 2022-11-01 at 5 35 08 AM" src="https://user-images.githubusercontent.com/18549210/199114869-6bcffd45-e7d3-41f3-9496-21a124a5129e.png">

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-11-03 03:09 UTC, adamhannigan approved these changes
Looks good to me. Just a small UI inconsistency with the Tab layout that we will need to tidy up before merging in 👍

2022-11-03 03:09 UTC, adamhannigan commented on src/features/community/scientist/ScientistModal.tsx
> +      <Panel className="relative max-w-5xl">
<img width="558" alt="Screen Shot 2022-11-03 at 2 04 30 pm" src="https://user-images.githubusercontent.com/11745561/199640244-5768edc0-ce5a-460e-99aa-bbfe8e5d2184.png">

For the 'tab' style you will need to put some padding at the top of your Panel. See attached for how tabs should appear.

2022-11-06 21:16 UTC, tiffanydys commented
> Looks good to me. Just a small UI inconsistency with the Tab layout that we will need to tidy up before merging in 👍 

Hi @adamhannigan, the UI changes are done and I've also added in the verified contracts deployed on mainnet. ❤️

2022-11-07 05:43 UTC, adamhannigan commented
@tiffanydys Looks good to me, just a small CI error at the moment

2022-11-07 05:58 UTC, tiffanydys commented
> @tiffanydys Looks good to me, just a small CI error at the moment

Pulled from main. Thanks @adamhannigan 😊

2022-11-07 22:10 UTC, spencerdezartsmith requested changes
It looks like when you updated to main there are a couple of import errors. I think the `nfts` folder was renamed to `sfts` in `assets`. Can you please update the imports?

2022-11-08 18:10 UTC, tiffanydys commented
> It looks like when you updated to main there are a couple of import errors. I think the `nfts` folder was renamed to `sfts` in `assets`. Can you please update the imports?

Edited the imports to one file and it seems to be okay now. Thanks!

2022-11-09 05:24 UTC, merged