[FEAT] Treasure Island Utilities
sunflower-land/sunflower-land pull request #2128
Opened 2023-01-30 22:31 UTC by HBandesh

# Description

In this PR, I have added treasure island utilities: Tiki Totem and Lunar Calendar. If Tiki Totem is placed, give a bonus +0.1 wood when chopping trees. If Lunar Calendar is placed, give a bonus 10% speed to crops (not fruit)

https://user-images.githubusercontent.com/35486909/215610872-b3b1a89f-2fe5-4db5-90c3-813e5cb4cd81.mov

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-01-30 23:00 UTC, Ivan-Ricardo-Lopes commented on src/features/game/events/landExpansion/plant.test.ts
> +  it("grows faster if Lunar calender is placed", () => {
```suggestion
  it("grows faster if Lunar calendar is placed.", () => {
```

2023-01-30 23:03 UTC, Ivan-Ricardo-Lopes commented on src/features/game/events/landExpansion/plant.test.ts
> +  it("applies a 10% speed boost with Lunar Calenda placed", () => {
```suggestion
  it("applies a 10% speed boost with Lunar Calendar placed.", () => {
```

2023-01-31 04:28 UTC, c-py requested changes
Looking good mate! Just one feedback on the descriptions.

2023-01-31 04:28 UTC, c-py commented on src/features/game/types/treasure.ts
> +    description: "A charm made from crops.",
```suggestion
    description: "Crops now follow the lunar cycle! 10% increase to crop growth speed.",
```

2023-01-31 04:28 UTC, c-py commented on src/features/game/types/treasure.ts
> +    description: "A charm made of wood.",
```suggestion
    description: "The Tiki Totem adds 0.1 wood to every tree you chop.",
```

2023-01-31 20:19 UTC, c-py approved these changes
LGTM! Nice work

2023-01-31 22:14 UTC, merged