[FEAT] AEO locking
sunflower-land/sunflower-land pull request #2579
Opened 2023-05-19 07:36 UTC by Rofrtd

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #issue

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-19 12:30 UTC, brian-man commented
Typo in PR title

2023-05-19 12:31 UTC, brian-man commented on src/features/game/events/landExpansion/moveCrop.ts
> +  const isBasicCrop =
Duplicate of `isBasicCrop` in plant.ts

2023-05-19 12:33 UTC, brian-man commented on src/features/game/events/landExpansion/removeCollectible.ts
> +    const collectible: PlacedLamp = collectibleToRemove;
This logic seems related to the genie lamp.  Why is it in a scarecrow block?

2023-05-19 12:34 UTC, brian-man commented on src/features/island/collectibles/MovableComponent.tsx
> +          crop.crop?.name === "Sunflower" ||
Shouldn't this use `isBasicCrop`?

2023-05-22 01:22 UTC, c-py requested changes

2023-05-22 01:22 UTC, c-py commented on src/features/island/collectibles/MovableComponent.tsx
> +  }
**issue (discussed):** I think this needs to call isAOE or similar, as the scarecrow cannot be dug up unless there are no crops planted.

2023-05-22 04:28 UTC, c-py approved these changes
LGTM!!

2023-05-22 04:29 UTC, merged