Move chum selection button in Fishing UI
sunflower-land/sunflower-land pull request #3158
Opened 2023-11-17 05:42 UTC by brian-man

# Description

In discord, user Tumbo reported
> I flubbed a couple of taps and fished without chum.
and recommended
> more separation between the chum “+” and “Cast” buttons

Good idea, IMO.

2023-11-19 22:55 UTC, spencerdezartsmith commented on src/features/island/fisherman/FishermanModal.tsx
> -          <Button
```
          <Button
            disabled={fishingLimitReached}
            className="h-11 w-12 min-w-max"
            onClick={() => setShowChum(true)}
          >
            <div className="flex items-center">
              <img src={plus} className="w-6 mt-1" />
            </div>
          </Button>
```

2023-11-19 22:57 UTC, spencerdezartsmith requested changes
I can see the issue that the player mentioned, however moving the button away from the help text doesn't make sense. I think it makes more sense to just increase the size of the button in place which forces more space between the chum and cast buttons. 

I have added some code in the comments.

<img width="363" alt="Screenshot 2023-11-20 at 9 54 49 am" src="https://github.com/sunflower-land/sunflower-land/assets/17863697/aa37bc69-7159-4602-a13a-439a8f27abc8">

2023-11-29 00:18 UTC, adamhannigan commented
Where have we settled with this initiative?

I agree with @spencerdezartsmith that the button needs to me mapped (in proximity) closely to the helper text about chum.

<img width="631" alt="Screenshot 2023-11-29 at 11 18 05 am" src="https://github.com/sunflower-land/sunflower-land/assets/11745561/7e034750-d933-438c-8436-9a886d750eaa">

2023-11-29 00:20 UTC, spencerdezartsmith commented
> Where have we settled with this initiative?
> 
> I agree with @spencerdezartsmith that the button needs to me mapped (in proximity) closely to the helper text about chum.
> 
> I do see how fat fingers can accidentally press it - we may need to figure out an alternative UI to support this
> 
> <img alt="Screenshot 2023-11-29 at 11 18 05 am" width="631" src="https://private-user-images.githubusercontent.com/11745561/286435995-7e034750-d933-438c-8436-9a886d750eaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMTc0OTUsIm5iZiI6MTcwMTIxNzE5NSwicGF0aCI6Ii8xMTc0NTU2MS8yODY0MzU5OTUtN2UwMzQ3NTAtZDkzMy00MzhjLTg0MzYtOWE4ODZkNzUwZWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAwMTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NDA3YWM3N2VmZTFjMTAyYTk0OGRkYWIxZjY2YjViNzM3YTA4ZjQxMDBlODdmNzhjMzdlN2RkODZlZTYyMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B_zN1qH8YWn61jdtbe7bqEAqli_436qE60hpIe4kIa4">

I haven't re run this but if the button is just a bit bigger in the position I mentioned, then I am happy to get this in.

2024-01-01 22:19 UTC, closed without merging

2024-01-01 22:19 UTC, adamhannigan commented
Closing for inactivity - it appears a consensus was not reached.

I think we need to revisit this with a new lens - perhaps some iconography for the chum action?