[FIX] NPC badges clickable from anywhere
sunflower-land/sunflower-land pull request #3569
Opened 2024-04-03 00:16 UTC by 0xSacul

# Description

For a long time now, clicking on NPC badges from anywhere would open their modal, this was known for a long time but not intended.

I've added a `checkDistanceToSprite(sprite, maxDistance)` function in BaseScene that can be called in any scene in the `on("pointerdown")` function. 

*not a bug, a feature*

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

local & yarn test
![image](https://github.com/sunflower-land/sunflower-land/assets/63975424/0888fa4e-6b40-4b7e-9c7c-b533a2ee6a44)

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-04-08 03:59 UTC, spencerdezartsmith requested changes
Nice job. I think this needs a bit more work so that it is consistant. Currently, the badges for the treasure chests are never clickable, its only the chest. 

However, the badges on Stella and Haz are. We should make them all clickable or all not. I think not makes sense and just leave the actual "thing" be clickable.

For Hammerin Haz, the badge isn't clickable from afar but the chest is. Probably should be put on the chest rather than the badge.

2024-04-11 23:48 UTC, spencerdezartsmith requested changes
Some of the required interactables have been removed. We will need these back. The badges are all not clickable which is fine. 

I think that Hammerin' Haz should also say "you're too far away" or whatever it is the other npc's say if you try to click on them and they're too far away. 

Also the goblin at the exchange has a box through his head. Not sure if the ordering of these sprites has somehow messed with his index.

2024-04-11 23:48 UTC, spencerdezartsmith commented on src/features/world/scenes/BeachScene.ts
> -    chest.setInteractive({ cursor: "pointer" }).on("pointerdown", () => {
I don't think we want to remove this interaction. I can't click on the wooden chest in the beach any more.

2024-04-11 23:48 UTC, spencerdezartsmith commented on src/features/world/scenes/RetreatScene.ts
> -    bank.setInteractive({ cursor: "pointer" }).on("pointerdown", () => {
We need this as well otherwise we can't open the bank.

2024-04-11 23:48 UTC, spencerdezartsmith commented on src/features/world/scenes/RetreatScene.ts
> -    wishingWell.setInteractive({ cursor: "pointer" }).on("pointerdown", () => {
We need this also.

2024-04-11 23:48 UTC, spencerdezartsmith commented on src/features/world/scenes/RetreatScene.ts
> -
We need all of this also. These interactables should just be on the building/npc so that we can interact with it.

2024-04-17 23:54 UTC, spencerdezartsmith reviewed
Tested and working well for me. 

One thing I think would be beneficial is adding the "I am too far away" on all the non npc clickables. Just because the cursor pointer is there when you hover over it but nothing happens if you're far away so the player might think its not working due to no feedback. Examples would be wishing well, chests, books. 

What do you think? Would you be keen to do that?

2024-04-17 23:57 UTC, 0xSacul commented
> Tested and working well for me.
> 
> One thing I think would be beneficial is adding the "I am too far away" on all the non npc clickables. Just because the cursor pointer is there when you hover over it but nothing happens if you're far away so the player might think its not working due to no feedback. Examples would be wishing well, chests, books.
> 
> What do you think? Would you be keen to do that?

Indeed that's a good idea! On my way to hunt every non npc clickables to add the text 👀 

*Will do that in a day or two, currently busy on other PRs*

2024-05-22 00:48 UTC, merged