[FEAT] New Items
sunflower-land/sunflower-land pull request #3631
Opened 2024-04-26 07:41 UTC by Rofrtd

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #issue

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-04-26 10:17 UTC, eliasSFL requested changes
Hey @Rofrtd Some standardisation and text fixes

2024-04-26 10:17 UTC, eliasSFL commented on metadata/metadata.ts
> +        value: 50,
```suggestion
        display_type: "boost_percentage",
        trait_type: "Green House Growth Time",
        value: -50,
```
Probably good to standardise this with other time reduction boosts

2024-04-26 10:17 UTC, eliasSFL commented on metadata/metadata.ts
> +    name: "Soybliss",
```suggestion
  "Grape Granny": {
    name: "Grape Granny",
```
Typo here probably

2024-04-26 10:17 UTC, eliasSFL commented on src/lib/i18n/dictionaries/englishDictionary.ts
> +    "An engine that boosts the Green House's growth speed by 50%.",
```suggestion
  "description.turbo.sprout":
    "An engine that reduces the Green House's growth time by 50%.",
```
Standardise with other time reduction boosts

2024-04-29 03:33 UTC, eliasSFL commented on src/lib/i18n/dictionaries/englishDictionary.ts
> +  "description.turbo.sprout.boost": "50% Green House Crop speed",
```suggestion
  "description.turbo.sprout.boost": "-50% Green House Crop Time",
```

2024-04-30 04:39 UTC, spencerdezartsmith approved these changes
LGTM

2024-04-30 05:17 UTC, merged