[FIX] Withdrawable lucky tresure items
sunflower-land/sunflower-land pull request #3879
Opened 2024-06-15 22:23 UTC by brian-man

2024-06-15 22:24 UTC, brian-man commented
> Adam — 02/13/2024 3:00 PM
> The Fox Hat, Chicken Hat + Pale Potion are this season's lucky treasure items.
>
> At the end of the season (end of April), you will be able to withdraw them

https://discord.com/channels/880987707214544966/880987707692687381/1207099016811380796

2024-06-16 01:40 UTC, eliasSFL requested changes

2024-06-16 01:40 UTC, eliasSFL commented on src/features/game/types/withdrawables.ts
> +  "Fox Hat": () => canWithdrawTimebasedItem(new Date("2024-05-01")),
```suggestion
  "Fox Hat": () => true,
```
Since the date already past should it be just `true`?

2024-06-16 01:40 UTC, eliasSFL commented on src/features/game/types/withdrawables.ts
> +  "Pale Potion": () => canWithdrawTimebasedItem(new Date("2024-05-01")),
```suggestion
  "Pale Potion": () => true,
```
Same here

2024-06-16 01:40 UTC, eliasSFL commented on src/features/game/types/withdrawables.ts
> +  "Chicken Hat": () => canWithdrawTimebasedItem(new Date("2024-05-01")),
```suggestion
  "Chicken Hat": () => true,
```
Same here

2024-06-24 01:02 UTC, spencerdezartsmith approved these changes
LGTM

2024-06-24 05:16 UTC, merged