[FEAT] Withdrawal Restriction for Crimstone Hammer
sunflower-land/sunflower-land pull request #3887
Opened 2024-06-16 13:32 UTC by eliasSFL

# Description

Withdrawal Restriction for Crimstone Hammer. 

We have to approach the withdrawal restriction fro Crimstone Hammer differently from Crimstone armour and amulet because the Hammer only needed to be equipped before mining the 4th mine for it to apply the +2 bonus to the 5th mine. We thought that adding a 7 day cooldown (5 days for full cycle + 2 day buffer) from the last Crimstone mine would be sufficient to prevent exploits with Crimstone Hammer Sharing. 

Fixes #issue

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-16 13:32 UTC, eliasSFL commented
This PR is to be merged after #3886

2024-06-24 01:16 UTC, spencerdezartsmith requested changes
Hey @eliasSFL would you mind adding some test cases for this one in `removeables.test.ts`? Just as the logic is a big more details it would be nice to see a test or two.

```
it("prevents a user from withdrawing/removing this item 1 days after using")
it("enables a user to withdraw/remove this item 7 days after using")
``` 

Also I think we would need to add a clearer restriction message. We need to user to understand there is a cooldown and potentially how long is remaining. Can you think of ways we might be able to communicate this?

2024-06-24 06:32 UTC, eliasSFL commented
@spencerdezartsmith 
> Hey @eliasSFL would you mind adding some test cases for this one in `removeables.test.ts`? Just as the logic is a big more details it would be nice to see a test or two.
> 
> ```
> it("prevents a user from withdrawing/removing this item 1 days after using")
> it("enables a user to withdraw/remove this item 7 days after using")
> ```
I can add the tests in `withdrawables.test.ts` for crimstone hammer and in `removables.test.ts` for grinx hammer. Will read through and see if there are other tests that I need to add

> Also I think we would need to add a clearer restriction message. We need to user to understand there is a cooldown and potentially how long is remaining. Can you think of ways we might be able to communicate this?
hmm Is there a const created somewhere that shows time left before withdrawal/removal? If not I can see if I can have a look at this one. Right now I'm thinking if we have a timer we can put like "Restricted for dd:hh:mm:ss" or something similar

2024-06-25 10:48 UTC, spencerdezartsmith reviewed
Nice job @eliasSFL. Just one suggestion on the test description.

2024-06-25 10:48 UTC, spencerdezartsmith commented on src/features/game/types/withdrawables.test.ts
> +    it("prevents withdrawal of Crimstone Hammer 7 days after last crimstone mine", () => {
Is this description correct? Should it read something like:
```suggestion
    it("prevents withdrawal of Crimstone Hammer if less than 7 days after last crimstone mine", () => {
```

2024-07-10 03:23 UTC, adamhannigan approved these changes
Makes sense 👍 Nice addition 👏

2024-07-10 03:23 UTC, merged