[CHORE] Update Login Settings Menu to be in line with Game Options implementation
sunflower-land/sunflower-land pull request #3907
Opened 2024-06-20 06:52 UTC by eliasSFL

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #issue

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-20 06:56 UTC, eliasSFL commented
This PR will cause conflicts with #3853 so have to update the other PR whichever PR merges in first

2024-06-24 05:24 UTC, spencerdezartsmith requested changes
This is generally good to go but I mentioned one refactor opportunity 🙏🏼

2024-06-24 05:24 UTC, spencerdezartsmith commented on src/features/auth/components/LoginSettings.tsx
> +  const Content = () => {
Hey @eliasSFL, I know you didn't create this component but now is a good time to refactor this as creating a "component" inside another component is generally bad practice. You can read about it [here](https://dev.to/sanjampreetsingh/nested-components-a-bad-practice-reactjs-1hbf). 

In this case this code inside of `Content` can just be moved inline in the JSX return like the below example:

```
{currentMenu !== "login" && <code>}
{currentMenu === "login" && <code>}
```

2024-06-24 05:51 UTC, eliasSFL commented
@spencerdezartsmith I have updated the code with your requested changes

2024-06-24 06:07 UTC, spencerdezartsmith approved these changes
👏🏼

2024-06-24 06:07 UTC, merged