[FEAT] Add a Back Button to the List of Sellable Items at Plaza Market
sunflower-land/sunflower-land pull request #4488
Opened 2024-10-03 10:21 UTC by Droidze

https://github.com/user-attachments/assets/33cdd5da-3c25-417c-8660-568effcb57b2

# What needs to be tested by the reviewer?
choose the List Trade Button by clicking bumpkin avatar -> trades tab or plaza trading board -> sell tab, and then click the Back Button.

2024-10-04 14:30 UTC, Alucard0389 commented
Nice thanks miss it since the beginning ❤️

2024-10-07 14:04 UTC, eliasSFL commented on src/features/bumpkins/components/Trade.tsx
> +            onClick={onBack}
You can use `onCancel` here instead of creating onBack since both of them are directing to the same function

2024-10-07 14:04 UTC, eliasSFL commented on src/features/bumpkins/components/Trade.tsx
> +}> = ({ inventory, onList, onCancel, onBack, isSaving, floorPrices }) => {
delete onBack

2024-10-07 14:04 UTC, eliasSFL commented on src/features/bumpkins/components/Trade.tsx
> +  onBack: () => void;
you can delete onBack

2024-10-07 14:04 UTC, eliasSFL commented on src/features/bumpkins/components/Trade.tsx
> +        onBack={() => setShowListing(false)}
Same here

2024-10-07 14:04 UTC, eliasSFL requested changes
Left some comments for changes

2024-10-07 14:38 UTC, Droidze commented
> You can use onCancel here instead of creating onBack since both of them are directing to the same function

2024-10-07 15:09 UTC, Droidze commented
> You can use onCancel here instead of creating onBack since both of them are directing to the same function

@eliasSFL  Initially, it was intended to use `OnCancel` for the back button, which was already present. However, to differentiate the left arrow's action (which is not truly canceling) from `OnCancel` and also using a related name, it was decided to use `OnBack` separately. This makes the code more readable for future developers.

Do you think `OnBack` makes any issues?

2024-10-14 01:12 UTC, eliasSFL approved these changes

2024-10-14 01:12 UTC, merged