[FEAT] Refactor Collectible Buff Labels
sunflower-land/sunflower-land pull request #4898
Opened 2024-12-08 13:05 UTC by eliasSFL

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #issue

# What needs to be tested by the reviewer?

Please describe how this can be tested.

# Checklist:

- [ ] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-12-08 13:05 UTC, eliasSFL commented
This PR is to be merged after #4894

2024-12-10 22:28 UTC, spencerdezartsmith requested changes
Nice one! Just some changes around accessing `state`.

2024-12-10 22:28 UTC, spencerdezartsmith commented on src/features/island/collectibles/components/Hourglass.tsx
> +  const [
It is a much better practice to implement `useSelector` here with a callback to get access just to the `state` value only. This follows the best practice recommendation of _least privilege - only accessing what you need_. Using `useActor` subscribes this component to ALL state changes in the machine which will then cause a re-render. We should always try to access only the data we need. I recommend refactoring all of these actors to selectors instead:

```ts
// Outside component
const _state = (state: MachineState) => state.context.state

// Inside component
const state = useSelector(gameService, _state)
```

2024-12-10 22:28 UTC, spencerdezartsmith commented on src/features/island/hud/components/codex/components/Detail.tsx
> +  const [
Same here

2024-12-10 22:28 UTC, spencerdezartsmith commented on src/features/marketplace/components/Collection.tsx
> +  const { gameService } = useContext(Context);
Same here

2024-12-10 22:28 UTC, spencerdezartsmith commented on src/features/marketplace/components/PurchaseModalContent.tsx
> +  const [
Same here

2024-12-10 22:28 UTC, spencerdezartsmith commented on src/features/marketplace/components/RemoveListing.tsx
> +  const [
Same here

2024-12-10 22:28 UTC, spencerdezartsmith commented on src/features/marketplace/components/RemoveOffer.tsx
> +  const [
Same here

2024-12-10 22:28 UTC, spencerdezartsmith commented on src/features/marketplace/components/TopTrades.tsx
> +  const [
Same here

2024-12-10 22:28 UTC, spencerdezartsmith commented on src/features/marketplace/components/TrendingTrades.tsx
> +  const [
You get the idea 😉

2024-12-11 10:31 UTC, eliasSFL commented
@spencerdezartsmith I've used your suggestions. 

So as much as possible I should just call the state using useSelector if I'm only accessing items in the GameState?

2024-12-12 03:06 UTC, spencerdezartsmith approved these changes
LGTM 👏🏼

2024-12-12 03:06 UTC, merged