[FIX] Remove Close Button Panel for Poppy Intro
sunflower-land/sunflower-land pull request #4949
Opened 2024-12-14 20:29 UTC by Droidze

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #issue

# What needs to be tested by the reviewer?

Please describe how this can be tested.

# Checklist:

- [ ] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [ ] I have read the contributing guidelines and agree to the T&Cs
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-12-15 01:04 UTC, eliasSFL requested changes
Instead of putting the speaking modal in NPCModals you could add the close button panel into with the deals component of the flower bounties

2024-12-15 01:05 UTC, eliasSFL commented on src/features/world/ui/flowerShop/FlowerBounties.tsx
>        <Deal
So close button panel here

2024-12-15 03:06 UTC, Droidze commented
> So close button panel here, and also at the return one below

@eliasSFL At the first thought about doing the easiest way, but also considered that you added `FlowerBounties` to Codex and could make issues there, so checked that 3 weeks ago you pulled out the `CloseButtonPanel` from `FlowerBounties` and added it to `NPCModals` for Poppy , probably it was not suitable to keep `CloseButtonPanel` inside. 

Briefly that's what happens when adding `CloseButtonPanel` inside `FlowerBounties`, shows it with two panels in Codex, which shouldn't be due to keeping consistency with other sections in this tab:

![image](https://github.com/user-attachments/assets/8b6d406e-db60-4aa0-ae2e-0ef3d2113de8)

2024-12-16 01:14 UTC, eliasSFL approved these changes
I have refactored the flower bounties modal so that we can use one for poppy and one for the codex, and it will also solve the double modal issue

2024-12-16 01:16 UTC, merged