[FEAT] Decorative Items - Homeless Tent & Nyon Statue
sunflower-land/sunflower-land pull request #563
Opened 2022-04-16 09:25 UTC by tiffanydys

# Description
- Added Homeless Tent near Home
- Added Nyon Statue NFT by the river

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
`yarn test`
<img width="374" alt="Screen Shot 2022-04-16 at 5 21 44 PM" src="https://user-images.githubusercontent.com/18549210/163669581-ae20c7dd-f557-4a14-82e0-2bf974148ac4.png">

`yarn dev`

### Ingredients:
<img width="498" alt="Screen Shot 2022-04-16 at 5 07 45 PM" src="https://user-images.githubusercontent.com/18549210/163669567-fb427eb9-08d3-421c-9c96-eafa2e06667e.png">
<img width="497" alt="Screen Shot 2022-04-16 at 5 08 47 PM" src="https://user-images.githubusercontent.com/18549210/163669566-4d3a9817-63fb-4a74-88d7-aeb982ab5bec.png">
<img width="497" alt="Screen Shot 2022-04-16 at 5 08 57 PM" src="https://user-images.githubusercontent.com/18549210/163669563-f02e100c-6e06-4e66-a0d8-2e934f528d47.png">

### In-Game:
<img width="494" alt="Screen Shot 2022-04-16 at 4 48 11 PM" src="https://user-images.githubusercontent.com/18549210/163669614-d7d79ea2-6c04-4be5-96c9-2dad320f22a5.png">

<img width="494" alt="Screen Shot 2022-04-16 at 5 14 37 PM" src="https://user-images.githubusercontent.com/18549210/163669619-bcaa1506-3d76-40ff-8a0d-e38d2885ee37.png">

<img width="494" alt="Screen Shot 2022-04-16 at 5 14 01 PM" src="https://user-images.githubusercontent.com/18549210/163669615-c4f3526d-2ff9-45a5-8ae5-39414984a8eb.png">

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-04-16 14:59 UTC, j923sneaks commented on src/features/game/types/images.ts
> +import homelessTemt from "assets/nfts/homeless_tent.png";
misspell

2022-04-16 18:01 UTC, Pranav-yadav requested changes
I would suggest to rename the "Nyon Statue Gold" to **"Golden Nyon Statue"** to keep name consistent with other Golden NFT's, both in code as well as png name 👍

2022-04-17 04:16 UTC, Z1kou commented on src/features/game/types/index.ts
> +  "Nyon Statue Gold": 423,
@Pranav-yadav  Legend

2022-04-17 14:35 UTC, tiffanydys commented on src/features/game/types/images.ts
> +import homelessTemt from "assets/nfts/homeless_tent.png";
Corrected. Thanks! :D

2022-04-17 14:36 UTC, tiffanydys commented on src/features/game/components/Decorations.tsx
> +import nyonStatueGold from "assets/nfts/nyon_statue_gold.png";
Updated. Thanks! ✌🏻

2022-04-17 14:36 UTC, tiffanydys commented on src/features/game/types/craftables.ts
> +  | "Nyon Statue Gold"
Updated. Thanks! ✌🏻

2022-04-17 14:36 UTC, tiffanydys commented on src/features/game/types/craftables.ts
> +  "Nyon Statue Gold": {
Updated. Thanks! ✌🏻

2022-04-17 14:36 UTC, tiffanydys commented on src/features/game/types/images.ts
> +import nyonStatueGold from "assets/nfts/nyon_statue_gold.png";
Updated. Thanks! ✌🏻

2022-04-17 14:36 UTC, tiffanydys commented on src/features/game/types/images.ts
> +  "Nyon Statue Gold": {
Updated. Thanks! ✌🏻

2022-04-17 14:36 UTC, tiffanydys commented on src/features/game/types/index.ts
> +  "Nyon Statue Gold": 423,
Updated. Thanks! ✌🏻

2022-04-18 02:59 UTC, adamhannigan commented
Thanks @tiffanydys 

Just a heads up, we will keep this PR open until we can build the backend/smart contract details

2022-04-21 04:12 UTC, merged

2022-04-21 05:08 UTC, adamhannigan commented
@tiffanydys Awesome work 👏 

For now we have just included one of the Nyon Statues. We have to be careful releasing too many decorative items. We want to release more NFT Buffs before we do more decorations 🤗 

Also, I noticed you manually created the markdown in the public/erc1155 folder.

We also have a `/markdown` folder. You can enter the details in a markdown file (e.g. `423.md`) and then run `yarn erc1155` to automatically update our JSON files 😄

2022-04-21 05:28 UTC, tiffanydys commented
> @tiffanydys Awesome work 👏 
> 
> 
> 
> For now we have just included one of the Nyon Statues. We have to be careful releasing too many decorative items. We want to release more NFT Buffs before we do more decorations 🤗 
> 
> 
> 
> Also, I noticed you manually created the markdown in the public/erc1155 folder.
> 
> 
> 
> We also have a `/markdown` folder. You can enter the details in a markdown file (e.g. `423.md`) and then run `yarn erc1155` to automatically update our JSON files 😄 

I didn't know we had that 👀 honestly was having a hard time editing it in one line 😅 should have figured it out that if it doesn't feel right then i'm probably doing it the wrong way lol. 
Thank you for the guidance! ❤️🤗