Ensure Polygon when using Metamask
sunflower-land/sunflower-land pull request #60
Opened 2021-12-31 21:57 UTC by chris-calo

A fun new PR for dealing with blockchain wallet providers (e.g. – Metamask). This emulates the behaviour of some DEXs, in which it tries to recover Polygon chain access if migrated away. Useful for when working with multiple chains, or if the user is off making trades and comes back to a previous session in a separate tab/window of Sunflower Farmers.

In the below example, I show initialising the app using the wrong network (BSC). Additionally, it shows switching tabs, choosing a different network, and then returning to the actively-running Sunflower Farmers game context. In contrast to other implementations I've seen, this will _not_ nag the user if they switch to a different chain while Sunflower Farmers is in an inactive tab/window.

_NOTE:_ I have only tested this with Metamask using Metamask-provided globals. However, to my knowledge, not only is Metamask one of the most used browser-based providers, but its behaviour is also widely adopted by competitors.

#### Example:

https://user-images.githubusercontent.com/3837103/147839775-2cd97a4b-e11a-43ad-824c-8b08096b90f9.mp4

2022-01-01 03:12 UTC, spencerdezartsmith approved these changes
🤩

2022-01-01 14:15 UTC, adamhannigan requested changes
Great work!  @chris-calo This should solve a lot of issues.

I found one small regression while manually testing. When changing the Network tab or MetaMask account the game is not reloading.

**Expected Behaviour**

1. Play the Game (connected to Polygon)
2. Change accounts
3. Farm reloads

1. Play the Game (connected to Polygon)
2. Change networks
3. Game reloads and warns that you are not on Polygon.

In this PR, the account change and network change events are not getting picked up and the game does not reload

2022-01-01 14:28 UTC, Rofrtd approved these changes
Awesome work!

2022-01-05 13:00 UTC, sweeper02 commented
> A fun new PR for dealing with blockchain wallet providers (e.g. – Metamask). This emulates the behaviour of some DEXs, in which it tries to recover Polygon chain access if migrated away. Useful for when working with multiple chains, or if the user is off making trades and comes back to a previous session in a separate tab/window of Sunflower Farmers.
> 
> In the below example, I show initialising the app using the wrong network (BSC). Additionally, it shows switching tabs, choosing a different network, and then returning to the actively-running Sunflower Farmers game context. In contrast to other implementations I've seen, this will _not_ nag the user if they switch to a different chain while Sunflower Farmers is in an inactive tab/window.
> 
> _NOTE:_ I have only tested this with Metamask using Metamask-provided globals. However, to my knowledge, not only is Metamask one of the most used browser-based providers, but its behaviour is also widely adopted by competitors.
> 
> #### Example:
>  Untitled.mp4

niceee

2022-01-20 00:42 UTC, closed without merging

2022-01-20 00:42 UTC, adamhannigan commented
Closing due to the new structure/refactor