[FEAT] Flexible bulk seed selling
sunflower-land/sunflower-land pull request #703
Opened 2022-04-26 12:11 UTC by Thimey

# Description

Add the option to sell custom amount of crops.

"Custom" button added below "Sell All" which allows farmers to use a range of increment/decrement buttons to adjust the amount they desire to sell. This button will show when farmer has > 10 crops to sell.

Addresses #693 

### Before

<img width="503" alt="image" src="https://user-images.githubusercontent.com/14039116/165296048-5ec1fc5a-01f8-47b7-ad3b-9a9ade88cd28.png">

### After

![bulkSell5](https://user-images.githubusercontent.com/14039116/166145985-6e81bc19-037c-456f-bb82-c183114ed296.gif)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

 - Manual test

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-04-26 14:04 UTC, JCtapuk commented
This functionality is convenient for the PC but not from a smartphone. I recommend adding a small button with a handle icon next to the sale on the right. When clicked, it will open a modal window in which you can click on 9 variations of the number buttons as well as 3 variations of the 25%, 50% and 100% buttons. This will give players a convenient way to specify the right amount or just click 50% and take if you have 200 pieces in your inventory then the number innput form will immediately indicate 100 pieces.
And 1 button is to clear the last character on the right if you made a mistake selecting quantities.

2022-04-26 14:18 UTC, alvinphoebeartemis commented
Why not like this? 😊 I think this is much better.![images (5).jpeg](https://user-images.githubusercontent.com/53922732/165321016-fd14b34d-d9cd-4873-b80a-b6dfef6e0b2e.jpeg)

2022-04-26 22:00 UTC, Thimey commented
@JCtapuk, yep good point! I'll have a play around with your idea and also @alvinphoebeartemis suggestion to see what works best

2022-04-27 17:09 UTC, Z1kou commented
I believe this feature has already been discussed by the devs and team a few weeks ago, the opinion's were different and at the end we settled to keep it as it is since we havent gotten a modal that is both simple and efficient both on PC and mobile !

2022-04-27 18:03 UTC, alvinphoebeartemis commented
Hi Team, @Z1kou @Thimey 

How about this UI/UX. 🤗
![image](https://user-images.githubusercontent.com/53922732/165590777-ae823c80-a14c-48d6-94fe-3ff2f06dc5c7.png)

2022-04-27 23:31 UTC, adamhannigan commented
@Thimey Hey mate great initiative 👏 

We've faced this issue a few times before and found the slider approach isn't very user friendly on the mobile. Where possible we take the button/click approach as it is intuitive on mobile especially.

Exploring some of the button approaches above seems like a good start 💪

2022-04-28 00:26 UTC, Thimey commented
Thanks @adamhannigan / @Z1kou - noted!

Nice work @alvinphoebeartemis! I'll play around with this - As Adam suggested, I'll try and come up with a solution with just buttons. 

A simple solution could be to add some +-1 and +- 10 buttons in the confirmation dialog and renaming the button to "Sell More" (I'm sure theres a better name for this, but you get the idea). This keeps the flow the same for selling all, but allows users to adjust before confirming.

I'll whip something up in the next couple of days 👍

2022-04-29 11:42 UTC, Thimey commented
@adamhannigan / @Z1kou - Updated based on feedback

Designed inspired by @alvinphoebeartemis 🙂 

I'll tidy up code once we're all  happy with UX.

2022-04-29 20:51 UTC, spencerdezartsmith commented
> Hi @Thimey 😊
> 
> I'm very impressed with the idea of pop-up when clicked the "Sell All" with your layout. ![image](https://user-images.githubusercontent.com/53922732/165989242-eaaa145a-ebf6-4eab-86f4-1c4a64b7e727.png) It gives me an idea for this mockup calculator-like. 😎
> 
> You may choose which one is better. **Mockup No. 1** ![image](https://user-images.githubusercontent.com/53922732/165988966-1cead275-e5b4-47db-8f26-04fccb7054c6.png)
> 
> **Mockup No. 2** ![image](https://user-images.githubusercontent.com/53922732/165989081-b804c6f0-5936-4708-955f-ea63275085da.png)
> 
> Sir @adamhannigan can also check on this 😉

I this the mock-up 1 is better suited as it will work well on mobile as well. It would be good to have this a reusable component that is particularly tied to the buy/sell flow.

2022-04-29 22:56 UTC, Thimey commented
oooh nice @alvinphoebeartemis!

However, I am wondering how often people would explicitly enter an amount to sell as opposed to incrementing/decrementing from total stock. It would be good to get some validation from others if this would save them time vs having a variety of different increment/decrement button +-1, +=10, +=20, MIN, MAX.

Adding explicit number entering would mean we need to think about overflow. Can they enter any number and stock overflow disables button and has some "invalid state" OR should they never be able to enter an amount greater than stock.

If we go with calculator style, we should at least include decrement buttons too.

Happy to implement either solution, but be great to get some more validation before committing 🙂

2022-04-29 23:52 UTC, adamhannigan commented
Great work so far 👏 

Just to add some thoughts. How often do we think that a user would want to sell a custom amount?

The typically workflow right now is plant -> harvest -> sell. For majority of users I predict they would click the 'Sell All' button.

Adding an extra step would add friction to this flow. I would suggest ensuring that the workflow is firstly suited to accomodate the majority of users and how they play. It should be the 5-10% who want to do a custom bulk sell that need to do an extra step.

2022-04-30 00:38 UTC, Thimey commented
Yep totally agree @adamhannigan. If we default to All and keep the option to edit in the confirmation dialog, there is no change to current "sell all" flow (2 clicks).

Since it is a less common flow to adjust the amount. I am leaning towards a collection of increment/decrement buttons over full calculator. This would be a simpler iteration and we can always change later to a calculator if it's needed.

2022-04-30 02:30 UTC, alvinphoebeartemis commented
Hi @Thimey , the default value will still the max available number of crops. To prevent hurting the User Experience. 🤗 No additional process at all.

2022-05-01 04:11 UTC, Thimey commented
Hey team, made a few changes, but decided not to go full calculator as I believe this is overkill and would be more clunky to use in a lot of situations.

 - Render increment buttons 1, 10, 50 depending on stock amount
 - Made the layout similar to @alvinphoebeartemis designs above, but with simpler buttons

As mentioned previously, there is no change to the flow of you want to sell all -> still 2 clicks with no changes.

**I'll update PR description once everyone is happy with the design**

![bulkSell4](https://user-images.githubusercontent.com/14039116/166131831-b18d6496-fb9a-4f84-957a-1a67519b6a59.gif)

### Variations

**<= 10**
<img width="509" alt="image" src="https://user-images.githubusercontent.com/14039116/166131691-607996fd-c678-42dd-9a3f-0841bb70eb8b.png">
**<= 50**
<img width="503" alt="image" src="https://user-images.githubusercontent.com/14039116/166131755-2861402f-b28f-40d4-81d2-084e2acf93c6.png">
**> 50**
<img width="500" alt="image" src="https://user-images.githubusercontent.com/14039116/166131737-d4638447-af00-48ea-bb18-f31fcc185f54.png">

2022-05-01 05:52 UTC, Pranav-yadav commented
Great idea's and implementations here so far.. 🚀
@Thimey I think we should separate the Custom Sell functionality from Sell All as, most of the players will be using Sell All directly and showing them Custom Functionality wouldn't be good, UX.. As, @adamhannigan has mentioned..

My suggestion:
Why not keep a another button named **Custom** for custom functionality, besides Sell All, this will improve the UX.. 😉

Let me know what you guys think..

2022-05-01 06:03 UTC, Thimey commented
Yeah nice one, @Pranav-yadav - makes sense to me. I'll update shortly

2022-05-01 12:48 UTC, Thimey commented
Fellow farmers 🧑‍🌾 

I've addressed the UX concerns and update the PR description so this should be reviewable now 👍

2022-05-03 06:52 UTC, Pranav-yadav requested changes

2022-05-03 07:44 UTC, Thimey commented on src/features/crops/components/Plants.tsx
> +            disabled={cropAmount.lessThanOrEqualTo(1)}
> Why not keep it < 5 ?

No big reason, just thought it wouldn't hurt (Technically less clicks to sell 4 😉). Happy to change though if we think it won't confuse people wondering why it's disabled.

> We should also focus on more clutter free UX for quick interactions.
> @Rofrtd would agree on this..

Are you suggesting another change or is this referring to the change mentioned above?

2022-05-03 09:06 UTC, Pranav-yadav commented on src/features/crops/components/Plants.tsx
> +            disabled={cropAmount.lessThanOrEqualTo(1)}
Yep. Actually what I was trying to say is that we should hide the Custom button for above mentioned conditions..

For more clutter free UI/UX.. 👍

2022-05-03 10:04 UTC, Thimey commented on src/features/crops/components/Plants.tsx
> +            disabled={cropAmount.lessThanOrEqualTo(1)}
Yep, was thinking the same thing... I think it's also worth checking for > 10 since anything less is still reasonable to sell single at time.

2022-05-03 12:47 UTC, Pranav-yadav commented on src/features/crops/components/Plants.tsx
> +            disabled={cropAmount.lessThanOrEqualTo(1)}
Definitely..
 `< 5` cause some crops cost higher (compared to sunflower xD) e.g. Wheat and Radish.. 
 the poor (noob) farmers should also be able to see the custom button. just taste of it.. 😉

2022-05-10 07:58 UTC, TeissierYannis commented
Hello, what do you think about that design #844 
I do a duplicate pr sorry for that boys

2022-05-11 05:36 UTC, alvinphoebeartemis commented
Hi @TeissierYannis thank you for bringing-in the idea. But for now we refrain from using manual input of numbers using inputbox. 😊 We suggest to have a ingame button to improve the UX. @Thimey has already a patch for this and we are waiting for the approval of the community. 😊 You may check our previous conversation on this PR. Thank you.

2022-05-23 04:34 UTC, adamhannigan commented
@Thimey Love the initiative mate 👏 

For now we are focussing our attention on a few of the upcoming game features and are putting a hold on large UI features getting added. This is to prevent application bloat and less items the team will need to maintain. The aim is to try free up as much time over the next 2-3 months so we can launch some amazing features 🤗

2022-05-23 04:34 UTC, closed without merging