[FEAT] Creates a button to add SFL token to MetaMask on successful withdraw of SFL token(s).
sunflower-land/sunflower-land pull request #832
Opened 2022-05-08 10:36 UTC by newb23

# Description

Creates a button to add SFL token to MetaMask on successful withdraw of SFL token(s).
Closes #828

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Local with `yarn test`. Also had to override the `error` state in GoblinLand.tsx to display the modal for testing.
Test Suites: 12 passed, 12 total
Tests:       103 passed, 103 total
Snapshots:   0 total
Time:        24.33 s
Ran all test suites.
Done in 
25.42s.
![firefox_Vqebi0QC51](https://user-images.githubusercontent.com/7065115/167292208-9e84a9f4-4dbc-49e4-a70f-7bf9377c01ab.png)
https://user-images.githubusercontent.com/7065115/167292215-5871805e-beb4-4984-93c4-641bc2d170ba.mp4

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-08 11:21 UTC, Pranav-yadav requested changes

2022-05-08 11:21 UTC, Pranav-yadav commented on src/features/game/components/Withdrawn.tsx
> +      <Button onClick={addTokenToMetamask}>Add SFL to MetaMask</Button>
add vertical margin `my-2` as suited..

2022-05-08 11:21 UTC, Pranav-yadav commented on src/features/game/components/Withdrawn.tsx
>        <Button onClick={() => goblinService.send("REFRESH")}>Ok</Button>
add margin bottom `mb-2` or `mb-3` as suited..

2022-05-09 00:47 UTC, merged

2022-05-09 00:54 UTC, baron commented
Shouldn't the token value be referenced from VITE_TOKEN_CONTRACT ?

2022-05-09 00:56 UTC, baron commented
Shouldn't the token contract address be referenced from TOKEN_CONTRACT?