[CHORE] "globalifies" the ReCaptcha SITEKEY for ease of change if needed later.
sunflower-land/sunflower-land pull request #856
Opened 2022-05-10 04:12 UTC by newb23

# Description

"globalifies" the ReCAPTCHA sitekey for ease of change if needed later.

## Type of change

Please delete options that are not relevant.

- [x] Chore

# How Has This Been Tested?

Test Suites: 12 passed, 12 total
Tests:       103 passed, 103 total
Snapshots:   0 total
Time:        19.454 s
Ran all test suites.
Done in 20.35s.

Monday, May 9, 2022 22:11:46

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [ ] Screenshot if it includes any UI changes
- [x] I have read the contributing guidelines and agree to the T&Cs
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-16 05:21 UTC, spencerdezartsmith requested changes
Great initiative! I think it makes more sense to move this key into the env file. Just left that comment.

2022-05-16 05:21 UTC, spencerdezartsmith commented on src/lib/config.ts
> +const SITEKEY = "6Lfqm6MeAAAAAFS5a0vwAfTGUwnlNoHziyIlOl1s";
It probably makes more sense to move this into the `.env.sample`. 🤔

2022-05-16 11:30 UTC, newb23 commented
@spencerdezartsmith 

I will move and test this just after the goblin modal PR +/- 10hrs from this comment.

2022-05-18 10:23 UTC, newb23 commented
Forgot to comment last night, but this is also completed. Moved the key into the .env.sample as requested!

2022-05-19 06:40 UTC, Rofrtd approved these changes
Hey @newb23 great improvement. 

Thanks for your contribution.
LGTM 🚀

2022-05-19 06:42 UTC, merged